### ISSUE TITLE
Lobechat 不支持 Nginx 反代的 copilot-gpt4-service

### ISSUE THREAD

**Issue by harisonkhlil** [aaamoon/copilot-gpt4-service#151]
## 环境：

Ubuntu 使用 `git clone` 以及 `docker compose up -d` 构建，并使使用 Nginx 反代到我自己购买的域名

## 其他客户端使用情况

1. OpenCat 没有任何问题
2. NextChat 没有任何问题

## LobeChat 问题详情

当时使用 `http://ip:8080/`  和 `https://mydomain` 作为 Proxy Url 时都无法使用，具体 check 如下：

```json
{
  "endpoint": "https://gp****ee.me/",
  "error": {
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-headers": "*",
      "access-control-allow-methods": "*",
      "access-control-allow-origin": "*",
      "connection": "keep-alive",
      "content-length": "18",
      "content-type": "text/plain; charset=utf-8",
      "date": "Thu, 11 Jan 2024 19:01:18 GMT",
      "server": "nginx/1.18.0 (Ubuntu)"
    },
    "stack": "Error: 405 Method Not Allowed\n    at W.generate (/app/.next/server/app/api/openai/chat/route.js:22:1855)\n    at tF.makeStatusError (/app/.next/server/app/api/openai/chat/route.js:22:13240)\n    at tF.makeRequest (/app/.next/server/app/api/openai/chat/route.js:22:13970)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async k (/app/.next/server/app/api/openai/chat/route.js:2:2906)\n    at async /app/.next/server/app/api/openai/chat/route.js:7:64510",
    "status": 405
  }
}
```

**Comment by magicnov** [comment]
Try to add /v1 path to end of host. Example: http://localhost:8090/v1

**Comment by harisonkhlil** [comment]
> Try to add /v1 path to end of host. Example: http://localhost:8090/v1

You're right
